name: Run tests

on:
  pull_request:

jobs:
  test:
    env:
      plugin_name: "otio_openassetio"

    name: Test
    strategy:
      matrix:
        python-version: [3.9]

    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Plugin
        run: |
          . dist/bin/activate
          pip install -e .[dev]

      - name: Lint with flake8
        run: |
          . dist/bin/activate
          flake8 --show-source --statistics otio_openassetio tests

      - name: Test with pytest
        run: |
          . dist/bin/activate
          pytest tests
        shell: bash
